#:kivy 1.1.0
#:import my pentai.gui.scale
# Use "my" own scaling due to issues with screen resolution and Kivy dp

# Globally set lots of size defaults
<Label>:
    font_size: my.dp(25)

# Labels for Settings screen
<SectionLabel@Label>:
    color: (0.5,0.5,0.5,1)

<SmallLabel>:
    font_size: my.dp(20)
    padding_x: my.dp(20)
    text_size: self.size

<TinyLabel>:
    font_size: my.dp(15)
    text_size: self.size
    padding_x: my.dp(20)
    color: (0.5,0.5,0.5,1)

<TextInput>:
    font_size: my.dp(30)

<MyCategoryLabel@Label>:
    font_size: my.dp(22)

<MyBigLabel@Label>:
    font_size: my.dp(30)
    bold: True

<CheckBoxList>:
    cols: 2

<ClickLabel>:
    halign: 'center'
    text_size: self.width, None

<MyCompositeListItem>:
    height: my.dp(60)
    rows: 2

<ConfirmPopup>:
    content:
    GridLayout:
        rows: 2
        Label:
            text: root.confirm_prompt
            font_size: my.dp(20)
        GridLayout:
            cols: 2
            MyButton:
                text: "Cancel"
                font_size: my.dp(20)
                on_release: root.clear()
            MyButton:
                text: "OK"
                font_size: my.dp(20)
                on_release: root.ok_confirm()

<GamesScreen>:
    GridLayout:
        cols: 1
        Label:
            text: "Unfinished Games"
            size_hint_y: .10

        GamesView:
            id: games_view

        GridLayout:
            rows: 1
            size_hint: (1, .1)
            MyButton:
                text: "Menu"
                on_release: root.app.show_menu_screen()
            MyButton:
                text: "Delete"
                on_release: root.delete_game()
            MyButton:
                text: "Edit"
                on_release: root.edit_game()
            MyButton:
                text: "Load"
                on_release: root.load_game()

<SLPart@Label>:
    size_hint_y: None
    text_size: (.95 * root.width), None
    height: self.texture_size[1]
    strip: False
    markup: True

<ScrollableLabel>:
    size_hint_y: .8
    GridLayout:
	    # This GridLayout and its children are due to an issue with
        # Kivy textures that are cannot be allocated because they are too big:
        # https://github.com/kivy/kivy/issues/2119
        id: gl_id
        cols: 1
        size_hint_x: 1
        height: self.minimum_height
        size_hint_y: None
        SLPart:
            text: root.text1
            id: label1_id
        SLPart:
            text: root.text2
            id: label2_id
        SLPart:
            text: root.text3
        SLPart:
            text: root.text4
        SLPart:
            text: root.text5
        SLPart:
            text: root.text6


<MenuScreen>:
    GridLayout:
        cols: 1
        Label:
            size_hint: 1, .1
            text: "PentAI by Bruce Cropley"

        SettingSpacer:
    
        ScrollableLabel:
            id: gl_id
            size_hint_x: 1
            text1: root.about_text1
            text2: root.about_text2
            text3: root.about_text3
            text4: root.about_text4
            text5: root.about_text5
            text6: root.about_text6
    
        GridLayout:
            cols: 1
            size_hint: 1, .5
    
            MyButton:
                id: new_game_id
                text: "New Game"
                on_release: root.app.show_new_game_screen()
    
            MyButton:
                text: "In Progress"
                on_release: root.app.show_games_screen()
    
            MyButton:
                text: "Edit Human Players"
                on_release: root.app.show_human_screen()
    
            MyButton:
                text: "Edit AI Players"
                on_release: root.app.show_ai_screen()
    
            MyButton:
                text: "Settings"
                on_release: root.app.show_settings_screen()
    
            MyButton:
                text: "Rules Demo"
                on_release: root.app.show_demo()
    
            MyButton:
                text: "Quit"
                on_release: root.app.prompt_quit()
    
            # TODO: Edit openings? Review completed games?

<SetupScreen>:
    GridLayout:
        cols: 1

        Label:
            text: "New Game"
            size_hint_y: .10

        SettingSpacer:

        GridLayout:
            cols: 2
            size_hint: 1, None
            height: my.dp(170)

            MyCategoryLabel:
                text: "Rules"

            MyCategoryLabel:
                text: "Board Size"

            Spinner:
                text: 'Standard'
                values: ['Standard', 'Tournament', '5-In-A-Row']
                      #, 'Keryo', 'Freestyle', 'No Captures']
                size_hint: (1, None)
                id: rules_id

            Spinner:
                text: '13'
                values: ['9', '13', '19']
                size_hint: (1, None)
                id: bs_id
            
        GridLayout:
            cols: 1
            size_hint_y: .3
            Label:
            Label:
                text: "Game Time (minutes each)"
            Label:

            GridLayout:
                size_hint_y: .5
                rows: 1
                Slider:
                    id: time_control_id
                    min: 0
                    max: 10
                    step: .5
                    value: root.time_control
                    on_value: root.time_control = (int(2*self.value)) / 2.0

                Label:
                    size_hint_x: .28
                    text: root.time_control_text(time_control_id.value)

        Label:
            size_hint_y: .05

        SettingSpacer:

        Label:
            text: "Players"
            size_hint_y: .11

        SettingSpacer:

        GridLayout:
            cols: 2
            size_hint_y: .75

            MyCategoryLabel:
                text: "Black Player"
                height: my.dp(48)

            MyCategoryLabel:
                text: "White Player"
                height: my.dp(48)

            CheckBoxList:
                # TODO: Horizontally centred
                group: 'black_type'
                values: ('Human', 'Computer')
                id: black_type_id
            CheckBoxList:
                # TODO: Horizontally centred
                group: 'white_type'
                values: ('Human', 'Computer')
                id: white_type_id

            # TODO: double click to edit player?
            Spinner:
                values: root.player_names[1]
                size_hint: (1, .8)
                id: bpl_id
            Spinner:
                values: root.player_names[2]
                size_hint: (1, .8)
                id: wpl_id

            MyButton:
                size_hint: (.2, .8)
                text: "Return"
                on_press: root.app.return_screen()

            MyButton:
                size_hint: (.2, .8)
                text: "Start Game"
                on_press: root.start_game()
                id: start_game_id



<AIPlayerScreen>:
    GridLayout:
        cols: 1
        Label:
            text: "Computer Player Editor"

        SettingSpacer:

        Label:
            text: 'Choose Player'

        Spinner:
            # TODO: double click to edit name
            text: root.current_name
            values: root.player_names
            size_hint: (1, 0.7)
            id: player_spinner_id

        TextInput:
            id: rename_id
            text: root.rename_text
            multiline: False

        Label:
            text: 'Search Parameters'

        SettingSpacer:

        BoxLayout:
            size_hint_y: None
            height: my.dp(48)

            Label:
                size_hint_x: .3
                text: 'Depth'

            Slider:
                id: depth_id
                min: 1
                max: 10
                # TODO: Test odd levels play ok
                step: 1
                value: root.genome.max_depth
                on_value: root.genome.max_depth = self.value

            Label:
                size_hint_x: .2
                text: '{}'.format(int(depth_id.value))

        BoxLayout:
            size_hint_y: None
            height: my.dp(48)

            Label:
                size_hint_x: .3
                text: 'Vision'

            Slider:
                id: vision_id
                min: 10
                max: 100
                step: 1
                value: root.genome.vision
                on_value: root.genome.vision = self.value

            Label:
                size_hint_x: .2
                text: '{}'.format(int(vision_id.value))

        BoxLayout:
            size_hint_y: None
            height: my.dp(48)

            Label:
                size_hint_x: .75
                text: 'Openings Book'

            CheckBox:
                # TODO: Turn this into a BigCheckBox class
                id: openings_id
                active: root.genome.use_openings_book
                on_active: root.genome.use_openings_book = self.active

                canvas:
                    Clear:
                    Color:
                        # Grey background
                        rgba: .6, .6, .6, .5
                    Rectangle:
                        size: 40, 40
                        pos: int(self.center_x - 20), int(self.center_y - 20)
                    Color:
                        rgba: .443, 0.848, 0.926, 1
                    Rectangle:
                        # TODO: Is this a local file?
                        source: 'atlas://data/images/defaulttheme/checkbox%s_%s' % (('_radio' if self.group else ''), ('on' if self.active else 'off'))
                        size: 60, 60
                        pos: int(self.center_x - 30), int(self.center_y - 30)

        SettingSpacer:

        Label:
            text: 'Position Evaluation'

        SettingSpacer:

        BoxLayout:
            size_hint_y: None
            height: my.dp(48)

            Label:
                text: 'Lines / Captures'

            Slider:
                id: captures_id
                min: 200
                max: 400
                step: 1
                value: root.genome.capture_score_base
                on_value: root.genome.capture_score_base = self.value

            Label:
                size_hint_x: .3
                text: '{}'.format(int(captures_id.value))

        BoxLayout:
            size_hint_y: None
            height: my.dp(48)

            Label:
                text: 'Judgement'
                halign: 'left'

            Slider:
                id: j_id
                min: 0
                max: 100
                value: root.genome.judgement
                on_value: root.genome.judgement = self.value

            Label:
                size_hint_x: .3
                text: '{}'.format(int(j_id.value))

        GridLayout:
            rows: 1 

            MyButton:
                text: "Menu"
                on_release: root.app.show_menu_screen()

            MyButton:
                text: "Cancel"
                on_release: root.cancel()

            MyButton:
                text: "Save"
                on_release: root.save()

            MyButton:
                text: "Help"
                on_release: root.show_help()

<HumanPlayerScreen>:
    GridLayout:
        cols: 1
        Label:
            text: "Human Player Editor"
            size_hint_y: .33

        SettingSpacer:

        Label:
            text: 'Choose Player'

        Spinner:
            # TODO: double click to edit name
            text: root.current_name
            values: root.player_names
            size_hint: (1, 0.35)
            id: player_spinner_id

        TextInput:
            id: rename_id
            text: root.rename_text
            multiline: False

        GridLayout:
            rows: 1 

            MyButton:
                text: "Menu"
                on_release: root.app.show_menu_screen()

            MyButton:
                text: "Cancel"
                on_release: root.cancel()

            MyButton:
                text: "Save"
                on_release: root.save()

            MyButton:
                text: "Help"
                on_release: root.show_help()

<ReviewButtons>:
    size_hint_x: .3
    cols: 1
    MyButton:
        text: "Play"
        on_release: root.ps.set_review_mode(False)
    MyButton:
        text: "Beginning"
        id: beginning_id
        on_release: root.ps.go_to_the_beginning()
    MyButton:
        text: "Back"
        on_release: root.ps.go_backwards_one()
    MyButton:
        text: "Forward"
        silent: True
        id: forward_id
        on_release: root.ps.go_forwards_one()
    MyButton:
        text: "Rematch"
        on_release: root.ps.rematch()
    MyButton:
        text: "Menu"
        on_release: root.ps.app.show_menu_screen()

<PlayButtons>:
    size_hint_x: .3
    cols: 1

    MyButton:
        text: "Review"
        id: review_id
        on_release: root.ps.set_review_mode(True)
    MyButton:
        text: "Take Back"
        on_release: root.ps.take_back_move()
    MyButton:
        text: "Settings"
        on_release: root.ps.app.show_settings_screen()
    MyButton:
        text: "Rematch"
        on_release: root.ps.rematch()
    MyButton:
        text: "Menu"
        on_release: root.ps.app.show_menu_screen()

<PenteScreen>:
    RelativeLayout:
        pos: self.parent.board_offset
        canvas:
            Rectangle:
                source: 'media/41-old-wooden-board.jpg'
                size: self.size
            Color:
                rgba: 0, 0, 0, 1
            Line:
                points: root.gridlines
                width: 2.0 * root.get_my_dp()
            Color:
                rgba: root.border_colour
            Line:
                #id: border_id
                points: root.border_lines
                joint: 'none'
                width: root.border_width
            Color:
                rgba: root.illegal_rect_color
            Rectangle:
                pos: root.illegal_rect_pos
                size: root.illegal_rect_size

        RelativeLayout:
            id: lower_horiz_grid_id
            pos: 0,0
            GridLayout:
                size_hint_x: 1
                rows: 1
        #Label:
            #text: root.h_grid_text
            #halign: 'justify'
            #color: 0, 0, 0, 1
            #size_hint_y: None
            #height: self.texture_size[1]
            #text_size: self.width - 20, None

    GridLayout:
        cols: 2
        size_hint: 1, None
        height: root.board_offset[1]
        canvas.before:
            Color:
                rgba: .3, .6, .9, 1
            Rectangle:
                # self here refers to the widget i.e GridLayout
                pos: self.pos
                size: self.size
        GridLayout:
            rows: 1

            GridLayout:
                # This is for switching panel buttons
                rows: 1
                size_hint: (.35, 1)
                id: panel_buttons_id
            
            GridLayout:
                rows: 2
                # TODO: duplication
                MyBigLabel:
                    id: black_time_id
                    #text: root.player_time[1]
                    #text: root.players[1].video_remaining_time
                    #text: root.get_remaining_time(1) # TODO: kivy import syntax for BLACK
                    text: ""
                    color: (0,0,0,1)
                MyBigLabel:
                MyBigLabel:
                    text: root.player_name[1]
                    color: (0,0,0,1)
                MyBigLabel:

                MyBigLabel:
                    id: white_time_id
                    text: ""
                    #text: root.player_time[2]
                    color: (1,1,1,1)
                MyBigLabel:
                MyBigLabel:
                    text: root.player_name[2]
                    color: (1,1,1,1)
                MyBigLabel:

    RelativeLayout:
        pos: (0,0)
        canvas:
            Color:
                rgba: root.confirm_rect_color
                id: 'confirm_rect'
            Rectangle:
                size: (root.size[0], self.parent.board_offset[1])

<SettingsScreen>:
    GridLayout:
        cols: 1

        Label:
            text: "PentAI Settings"
            size_hint_y: .15

        SettingSpacer:

        SectionLabel:
            text: "User Interface"
            size_hint_y: .15

        SettingSpacer:

        SwitchSetting:
            text: "Mark Moves"
            desc: "Mark the last two moves, each with a dot in the centre"
            key: "mark_moves"

        SettingSpacer:

        SwitchSetting:
            text: "Show Captures"
            desc: "Show pieces that were captured last move as transparent ghost pieces"
            key: "mark_captures"

        SettingSpacer:

        OptionsSetting:
            text: "Move Confirmation"
            values: ("None Required", "Off Board", "On Piece")
            desc: "For small screens or while travelling"
            key: "move_confirmation"

        SettingSpacer:

        SliderSetting:
            text: "Minimum Wait Time"
            desc: "Minimum time to wait for the AI to play (secs)"
            min: 0
            max: 2
            step: .1
            key: "minimum_wait"
                    #text: "%.1f" % s_id.value

        SettingSpacer:

        SwitchSetting:
            text: "Show Confirmation Popups"
            desc: "For major actions such as exiting"
            key: "confirm_popups"

        SettingSpacer:

        SectionLabel:
            text: "Sound"
            size_hint_y: .15

        SettingSpacer:

        SliderSetting:
            text: "Effects Volume"
            desc: "How loud should the sound effects be?"
            min: 0
            max: 1
            key: "effects_volume"
            display_factor: 100
            on_value: root.adjust_volumes()

        SettingSpacer:

        SwitchSetting:
            text: "Tick"
            desc: "Should the clock make a ticking sound?"
            key: "tick"

        SettingSpacer:

        SliderSetting:
            text: "Music Volume"
            desc: "How loud should the music be?"
            min: 0
            max: 1
            key: "music_volume"
            display_factor: 100
            on_value: root.adjust_volumes()

        Button:
            size_hint_y: .2
            text: "Return"
            on_press: root.app.return_screen()


<Piece>:
    Image:
        id: image
        source: root.source
        center: 0, 0

