#:kivy 1.1.0
#:import kivy kivy
#:import win kivy.core.window

<Label>:
    font_size: sp(25)

<CheckBoxList>:
    cols: 2

<MyCompositeListItem>:
    height: 60
    rows: 2

<MyButton>:
    font_size: '25sp'

<ConfirmPopup>:
    content:
    GridLayout:
        rows: 2
        Label:
            text: root.confirm_prompt
            font_size: '20sp'
        GridLayout:
            cols: 2
            MyButton:
                text: "Cancel"
                font_size: '20sp'
                on_release: root.clear()
            MyButton:
                text: "OK"
                font_size: '20sp'
                on_release: root.ok_confirm()

<GamesScreen>:
    GridLayout:
        rows: 2

        GamesView:
            id: games_view

        GridLayout:
            rows: 1
            size_hint: (1, .1)
            MyButton:
                text: "Return"
                on_release: root.app.return_screen()
            MyButton:
                text: "Delete"
                on_release: root.delete_game()
            MyButton:
                text: "Edit"
                on_release: root.edit_game()
            MyButton:
                text: "Load"
                on_release: root.load_game()

<MenuScreen>:
    GridLayout:
        cols: 1
        size_hint: 1, .5

        MyButton:
            id: new_game_id
            text: "New Game"
            on_release: root.app.show_new_game_screen()

        MyButton:
            text: "Saved Games"
            on_release: root.app.show_games_screen()

        MyButton:
            text: "Edit AI Players"
            on_release: root.app.show_ai_screen()

        MyButton:
            text: "Review Game"
            # TODO

        MyButton:
            text: "Settings"
            on_release: root.app.show_settings_screen()

        MyButton:
            text: "Show Demo"
            on_release: root.app.show_demo()

        # TODO: Edit openings?

#Help
#Music volume
#Start/Resume

<SetupScreen>:
    GridLayout:
        cols: 1
        GridLayout:
            cols: 2
            size_hint: 1, None
            height: 170

            MyLabel:
                text: "Rules"

            MyLabel:
                text: "Board Size"

            Spinner:
                text: 'Standard'
                values: ['Standard', 'Tournament', '5-In-A-Row']
                      #, 'Keryo', 'Freestyle', 'No Captures']
                size_hint: (1, None)
                id: rules_id

            Spinner:
                text: '13'
                values: ['9', '13', '19']
                size_hint: (1, None)
                id: bs_id
            
        GridLayout:
            cols: 1
            size_hint_y: .3
            Label:

            Label:
                text: "Players"

        GridLayout:
            cols: 2
            size_hint_y: .9

            MyLabel:
                text: "Black Player Type"
                height: '48sp'

            MyLabel:
                text: "White Player Type"
                height: '48sp'

            CheckBoxList:
                group: 'black_type'
                values: ('Human', 'Computer')
                id: black_type_id
            CheckBoxList:
                group: 'white_type'
                values: ('Human', 'Computer')
                id: white_type_id

            # TODO: double click to edit player?
            Spinner:
                values: root.player_names[1]
                size_hint: (1, None)
                id: bpl_id
            Spinner:
                values: root.player_names[2]
                size_hint: (1, None)
                id: wpl_id

            MyButton:
                size_hint: (.2, .4)
                text: "Return"
                on_press: root.app.return_screen()

            MyButton:
                size_hint: (.2, .4)
                text: "Start Game"
                on_press: root.start_game()
                id: start_game_id


# Globally set all Labels
<MyLabel@Label>:
    font_size: '25sp'

<MyBigLabel@Label>:
    font_size: '30sp'
    bold: True

<AIPlayerScreen>:
    GridLayout:
        cols: 1
        Label:
            text: "Computer Player Editor"
        # Line:
            # TODO: <hr> equivalent

        Label:
            text: 'Choose Player'

        Spinner:
            # TODO: double click to edit name
            text: root.current_name
            values: root.player_names
            size_hint: (1, None)
            id: player_spinner_id

        TextInput:
            id: rename_id
            text: root.rename_text
            font_size: '25sp'

        Label:
            text: 'Search Parameters'

        BoxLayout:
            size_hint_y: None
            height: '48sp'

            Label:
                size_hint_x: .3
                text: 'Depth'

            Slider:
                id: depth_id
                min: 1
                max: 10
                # TODO: Test odd levels play ok
                step: 1
                value: root.genome.max_depth
                on_value: root.genome.max_depth = self.value

            Label:
                size_hint_x: .2
                text: '{}'.format(int(depth_id.value))

        BoxLayout:
            size_hint_y: None
            height: '48sp'

            Label:
                size_hint_x: .3
                text: 'Vision'

            Slider:
                id: vision_id
                min: 10
                max: 100
                step: 1
                value: root.genome.vision
                on_value: root.genome.vision = self.value

            Label:
                size_hint_x: .2
                text: '{}'.format(int(vision_id.value))

        BoxLayout:
            size_hint_y: None
            height: '48sp'

            Label:
                size_hint_x: .75
                text: 'Openings Book'

            CheckBox:
                id: openings_id
                active: root.genome.use_openings_book
                on_active: root.genome.use_openings_book = self.active

                canvas:
                    Clear:
                    Color:
                        # Grey background
                        rgba: .6, .6, .6, .5
                    Rectangle:
                        size: 40, 40
                        pos: int(self.center_x - 20), int(self.center_y - 20)
                    Color:
                        rgba: .443, 0.848, 0.926, 1
                    Rectangle:
                        # TODO: Is this a local file?
                        source: 'atlas://data/images/defaulttheme/checkbox%s_%s' % (('_radio' if self.group else ''), ('on' if self.active else 'off'))
                        size: 60, 60
                        pos: int(self.center_x - 30), int(self.center_y - 30)

        Label:
            text: 'Position Evaluation'

        BoxLayout:
            size_hint_y: None
            height: '48sp'

            Label:
                text: 'Lines / Captures'

            Slider:
                id: captures_id
                min: 200
                max: 400
                step: 1
                value: root.genome.capture_score_base
                on_value: root.genome.capture_score_base = self.value

            Label:
                size_hint_x: .3
                text: '{}'.format(int(captures_id.value))

        BoxLayout:
            size_hint_y: None
            height: '48sp'

            Label:
                text: 'Misjudgement'
                halign: 'left'

            Slider:
                id: mj_id
                min: 0
                max: 50
                value: root.genome.misjudgement
                on_value: root.genome.misjudgement = self.value

            Label:
                size_hint_x: .3
                text: '{}'.format(int(2*mj_id.value))

        GridLayout:
            rows: 1 

            MyButton:
                text: "Return"
                on_release: root.app.return_screen()

            MyButton:
                text: "Cancel"
                on_release: root.cancel()

            MyButton:
                text: "Save"
                on_release: root.save()

<ReviewButtons@GridLayout>:
    size_hint_x: .3
    cols: 1
    MyButton:
        text: "Play"
        on_release: root.ps.set_review_mode(False)
    MyButton:
        text: "Beginning"
        on_release: root.ps.go_to_the_beginning()
    MyButton:
        text: "Back"
        on_release: root.ps.go_backwards_one()
    MyButton:
        text: "Forward"
        on_release: root.ps.go_forwards_one()
    MyButton:
        text: "End"
        on_release: root.ps.go_to_the_end()
    MyButton:
        text: "Rematch"
        on_release: root.ps.rematch()

<PlayButtons>:
    size_hint_x: .3
    cols: 1

    MyButton:
        text: "Review"
        on_release: root.ps.set_review_mode(True)
    MyButton:
        text: "Settings"
        on_release: root.ps.app.show_settings_screen()
    MyButton:
        text: "Menu"
        on_release: root.ps.app.show_menu_screen()

<PenteScreen>:
    RelativeLayout:
        pos: self.parent.board_offset
        canvas:
            Rectangle:
                source: 'media/41-old-wooden-board.jpg'
                size: self.size
            Color:
                rgba: 0, 0, 0, 1
            Line:
                points: root.gridlines
                width: 2.0
            Color:
                rgba: root.border_colour
            Line:
                points: root.border_lines
                joint: 'none'
                width: 6

    GridLayout:
        cols: 2
        size_hint: 1, None
        height: root.board_offset[1]
        canvas.before:
            Color:
                rgba: .3, .6, .9, 1
            Rectangle:
                # self here refers to the widget i.e GridLayout
                pos: self.pos
                size: self.size
        GridLayout:
            rows: 1

            GridLayout:
                # This is for switching panel buttons
                rows: 1
                size_hint: (.35, 1)
                id: panel_buttons_id
            
            GridLayout:
                rows: 2
                # TODO: duplication
                MyBigLabel:
                    # TODO: times
                    text: root.player_time[1]
                    color: (0,0,0,1)
                MyBigLabel:
                MyBigLabel:
                    text: root.player_name[1]
                    color: (0,0,0,1)
                MyBigLabel:

                MyBigLabel:
                    # TODO: times
                    text: root.player_time[2]
                    color: (1,1,1,1)
                MyBigLabel:
                MyBigLabel:
                    text: root.player_name[2]
                    color: (1,1,1,1)
                MyBigLabel:

    RelativeLayout:
        pos: (0,0)
        canvas:
            Color:
                rgba: root.confirm_rect_color
                id: 'confirm_rect'
            Rectangle:
                size: (root.size[0], self.parent.board_offset[1])

<Piece>:
    Image:
        id: image
        source: root.source
        center: 0, 0

