#:kivy 1.1.0
#:import kivy kivy
#:import win kivy.core.window

<Label>:
    font_size: dp(25)

<CheckBoxList>:
    cols: 2

<ConfirmPopup>:
    content:
    GridLayout:
        rows: 2
        Label:
            text: root.confirm_prompt
            font_size: '20sp'
        GridLayout:
            cols: 2
            Button:
                text: "Cancel"
                font_size: '20sp'
                on_release: root.clear()
            Button:
                text: "OK"
                font_size: '20sp'
                on_release: root.ok_confirm()

<GamesScreen>:
    GridLayout:
        rows: 2

        GamesView:
            id: games_view

        GridLayout:
            rows: 1
            size_hint: (1, .07)
            Button:
                text: "Delete"
                on_release: root.delete_game()
            Button:
                text: "Edit"
                on_release: root.edit_game()
            Button:
                text: "Load"
                on_release: root.load_game()

<MenuScreen>:
    GridLayout:
        cols: 1
        size_hint: 1, .5

        Button:
            text: "New Game"
            on_release: root.app.show_new_game_screen()

        Button:
            text: "Saved Games"
            on_release: root.app.show_games_screen()

        Button:
            text: "Edit AI Players"
            on_release: root.app.show_ai_screen()

        Button:
            text: "Review Game"
            # TODO

        Button:
            text: "Options"
            on_release: root.app.show_options()

        Button:
            text: "Show Demo"
            # TODO

        # TODO: Edit openings?

#Help
#Sound effects volume
#Music volume
#Start/Resume

# Player selection: Spinner
<NewGameScreen>:
    GridLayout:
        cols: 1
        GridLayout:
            cols: 2
            size_hint: 1, None
            height: 200

            CheckBoxList:
                text: 'Rules'
                group: 'rules'
                # TODO: Get these from the rules class
                values: ['Standard', 'Tournament', 'Keryo', 'Freestyle', '5-In-A-Row', 'No Captures']
                id: rules_id

            CheckBoxList:
                text: 'Board Size'
                group: 'board_size'
                values: ['9', '13', '19']
                id: bs_id

            
        GridLayout:
            cols: 2
            height:120

            GridLayout:
                cols:2
                height:120
                MyLabel:
                    text: 'Black\nPlayer\nName'
                TextInput
                    text: 'Black'
                    id: black_name_id
                CheckBoxList:
                    group: 'black_type'
                    text: ''
                    values: ('Human', 'Computer')
                    id: black_type_id

            GridLayout:
                cols:2
                height:50
                MyLabel:
                    text: 'White\nPlayer\nName'
                TextInput
                    text: 'White'
                    id: white_name_id
                CheckBoxList:
                    group: 'white_type'
                    text: ''
                    values: ('Human', 'Computer')
                    id: white_type_id

            CheckBoxList:
                group: 'max_depth'
                text: 'Max Depth'
                values: ('0', '2', '4', '6', '7', '8', '10', '12')
                id: max_depth_id

            Button:
                size_hint: (.2, .2)
                text: 'Start Game'
                on_press: root.start_game()
                id: start_button

<SetupScreen>:
    GridLayout:
        cols: 1
        GridLayout:
            cols: 2
            size_hint: 1, None
            height: 200


            CheckBoxList:
                text: 'Rules'
                group: 'rules'
                # TODO: Get these from the rules class
                values: ['Standard', 'Tournament', 'Keryo', 'Freestyle', '5-In-A-Row', 'No Captures']
                id: rules_id

            CheckBoxList:
                text: 'Board Size'
                group: 'board_size'
                values: ['9', '13', '19']
                id: bs_id

            
        GridLayout:
            cols: 2
            height:120

            GridLayout:
                cols:2
                height:120
                MyLabel:
                    text: 'Black\nPlayer\nName'
                TextInput
                    text: 'Black'
                    id: black_name_id
                CheckBoxList:
                    group: 'black_type'
                    text: ''
                    values: ('Human', 'Computer')
                    id: black_type_id

            GridLayout:
                cols:2
                height:50
                MyLabel:
                    text: 'White\nPlayer\nName'
                TextInput
                    text: 'White'
                    id: white_name_id
                CheckBoxList:
                    group: 'white_type'
                    text: ''
                    values: ('Human', 'Computer')
                    id: white_type_id

            CheckBoxList:
                group: 'max_depth'
                text: 'Max Depth'
                values: ('0', '2', '4', '6', '7', '8', '10', '12')
                id: max_depth_id

            Button:
                size_hint: (.2, .2)
                text: 'Start Game'
                on_press: root.start_game()
                id: start_button


# Globally set all Labels
<MyLabel@Label>:
    font_size: '25sp'

<AIPlayerScreen>:
    GridLayout:
        cols: 1
        Label:
            text: "Computer Player Editor"

        Label:
            text: 'Player'

        Spinner:
            #TODO: double click to edit name
            text: root.current_name
            values: root.player_names
            size_hint: (1, None)
            id: player_spinner_id

        Label:
            text: 'Search'

        BoxLayout:
            size_hint_y: None
            height: '48dp'

            Label:
                text: 'Depth'

            Slider:
                id: depth
                min: 2
                max: 10
                # TODO: Test odd levels play ok
                step: 1
                value: root.genome.max_depth
                on_value: root.genome.max_depth = self.value

        BoxLayout:
            size_hint_y: None
            height: '48dp'

            Label:
                text: 'Vision'

            Slider:
                id: vision
                min: 60
                max: 100
                step: 1
                value: root.genome.vision
                on_value: root.genome.vision = self.value

        BoxLayout:
            size_hint_y: None
            height: '48dp'

            Label:
                text: 'Width'

            Slider:
                id: width
                min: 6
                max: 12
                step: 1
                value: root.genome.mmpdl
                on_value: root.genome.mmpdl = self.value

        BoxLayout:
            size_hint_y: None
            height: '48dp'

            Label:
                text: 'Openings Book'

            CheckBox:
                # TODO: The tick image is a bit small
                id: openings
                active: root.genome.use_openings_book
                on_active: root.genome.use_openings_book = self.active

        BoxLayout:
            size_hint_y: None
            height: '48dp'

            Label:
                text: 'Lines / Captures'

            Slider:
                id: capture_pref
                min: 200
                max: 400
                step: 1
                value: root.genome.capture_score_base
                on_value: root.genome.capture_score_base = self.value

        GridLayout:
            rows: 1 

            Button:
                text: "Menu"
                on_release: root.menu()

            Button:
                text: "Cancel"
                on_release: root.cancel()

            Button:
                text: "Save"
                on_release: root.save()


<PenteScreen>:
    RelativeLayout:
        pos: self.parent.board_offset
        canvas:
            Rectangle:
                source: 'media/41-old-wooden-board.jpg'
                size: self.size
            Color:
                rgba: 0, 0, 0, 1
            Line:
                points: root.gridlines
                width: 2.0
            Color:
                rgba: root.border_colour
            Line:
                points: root.border_lines
                joint: 'none'
                width: 6

    GridLayout:
        cols: 2
        size_hint: 1, None
        height: root.board_offset[1]
        canvas.before:
            Color:
                rgba: 0, 0, .5, 1
            Rectangle:
                # self here refers to the widget i.e GridLayout
                pos: self.pos
                size: self.size
        GridLayout:
            rows: 1

            GridLayout:
                size_hint_x: .3
                cols: 1
                Button:
                    font_size: '20sp'
                    text: "Options"
                    on_release: root.app.show_options()
                Button:
                    font_size: '20sp'
                    text: "Beginning"
                    on_release: root.go_to_the_beginning()
                Button:
                    font_size: '20sp'
                    text: "Back"
                    on_release: root.go_backwards_one()
                Button:
                    font_size: '20sp'
                    text: "Forward"
                    on_release: root.go_forwards_one()
                Button:
                    font_size: '20sp'
                    text: "End"
                    on_release: root.go_to_the_end()
            GridLayout:
                rows: 2
                # TODO: duplication
                MyLabel:
                    # TODO: times
                    # TODO: BLACK/WHITE
                    text: root.player_time[1]
                MyLabel:
                MyLabel:
                    text: root.player_name[1]
                MyLabel:
    
                MyLabel:
                    # TODO: times
                    text: root.player_time[2]
                MyLabel:
                MyLabel:
                    text: root.player_name[2]
                MyLabel:

    RelativeLayout:
        pos: (0,0)
        canvas:
            Color:
                rgba: root.confirm_rect_color
                #1, 0, 0, .5
                id: 'confirm_rect'
            Rectangle:
                size: (root.size[0], self.parent.board_offset[1])

<Piece>:
    Image:
        id: image
        source: root.source
        center: 0, 0

