
<AIHelpScreen>:
    title: "AI Player Help"

<AIHelpText>:
    Section:
        continuation: True
        text: root.intro_text
        
    HSpacer:
    Section:
        title: "Properties"
        text: root.properties_text
 
    HSpacer:
    Section:
        title: "Openings Book"
        text: root.openings_text
 
    HSpacer:
    Section:
        title: "Profiles"
        text: root.profiles_text

